name: Integration Update
description: Template for updating an existing integration
labels: ["integration-update"]
body:
  - type: markdown
    attributes:
      value: |
        ## Description

        Please describe the changes made to the existing integration and why they were necessary. Include any relevant context, such as bug fixes, feature updates, or improvements to configuration.

        ## Checklist

        - [ ] **Validated in Customer Environment:** Changes have been tested in a customer environment and verified to work as expected.
        - [ ] **Updated README:** The README has been updated to reflect any changes to configuration, setup, or usage.