name: New Integration
description: Template for adding a new integration
labels: ["new-integration"]
body:
  - type: markdown
    attributes:
      value: |
        ## Description

        Please provide a brief description of your changes and the context for this integration. Include any background details or links to related issues.

        ## Checklist

        - [ ] **New Integration Folder:** A new folder has been created for the integration.
        - [ ] **Updated README:** The README has been updated based on the boilerplate to reflect the new integration details.
        - [ ] **customer-integration.star File:** The `customer-integration-<name>.star` file has been created/updated as required.
        - [ ] **config.json File:** The `config.json` is updated with the `name` (product name) and `type` (inbound or outbound) of integration
